name: Deploy to Infomaniak

on:
  push:
    branches: [main] # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Infomaniak hosting
    steps:
      - name: ‚¨áÔ∏è Checkout
        uses: actions/checkout@v4

      - name: ‚öôÔ∏è Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üß± Build UI
        working-directory: ui
        run: |
          npm ci
          npm run build

      - name: üöÄ Upload UI to /public
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: ui/dist/*
          # Looks like it copies ui/dist/* to /public/ui/dist/* on server
          target: ${{ vars.DEPLOY_DIR }}

      - name: üöÄ Git fetch and reset on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${{ vars.DEPLOY_DIR }}
            rm -rf public/ # Clear out old files
            git fetch origin
            git reset --hard origin/main # public/ is re-created from repo
            mv ui/dist/* public/ # Move built files to public/
            cd api
            /opt/php8.4/bin/composer install --no-dev --optimize-autoloader
            /opt/php8.4/bin/php artisan migrate --force
            /opt/php8.4/bin/php artisan config:clear
            /opt/php8.4/bin/php artisan config:cache
            /opt/php8.4/bin/php artisan route:clear
            /opt/php8.4/bin/php artisan route:cache
            /opt/php8.4/bin/php artisan view:clear
            /opt/php8.4/bin/php artisan view:cache
